# Generated by Django 5.2.3 on 2025-06-12 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('codice_evento', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('data', models.DateField()),
                ('ora_inizio', models.TimeField(blank=True, null=True)),
                ('ora_fine', models.TimeField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=20, null=True)),
                ('genere', models.CharField(blank=True, max_length=50, null=True)),
                ('prezzo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('numero_partecipanti', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'evento',
            },
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('codice_artista', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'artista',
            },
        ),
        migrations.CreateModel(
            name='Pr',
            fields=[
                ('codice_pr', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('cognome', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'pr',
            },
        ),
        migrations.CreateModel(
            name='RichiestaPrenotazioneSerata',
            fields=[
                ('codice_richiesta', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('numero_invitati', models.IntegerField(blank=True, null=True)),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('stato', models.CharField(max_length=9)),
                ('ora_inizio', models.TimeField(blank=True, null=True)),
                ('ora_fine', models.TimeField(blank=True, null=True)),
                ('data_serata', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'richiesta_prenotazione_serata',
            },
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id_utente', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('cognome', models.CharField(max_length=50)),
                ('data_di_nascita', models.DateField()),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('ruolo', models.CharField(max_length=7)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'utente',
            },
        ),
        migrations.CreateModel(
            name='ListaPr',
            fields=[
                ('codice_lista', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nome_lista', models.CharField(blank=True, max_length=50, null=True)),
                ('codice_evento', models.ForeignKey(blank=True, db_column='codice_evento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.evento')),
                ('codice_pr', models.ForeignKey(blank=True, db_column='codice_pr', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.pr')),
            ],
            options={
                'db_table': 'lista_pr',
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='codice_richiesta',
            field=models.ForeignKey(blank=True, db_column='codice_richiesta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.richiestaprenotazioneserata'),
        ),
        migrations.CreateModel(
            name='Tavolo',
            fields=[
                ('codice_tavolo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('posti_massimi', models.IntegerField(blank=True, null=True)),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
                ('area', models.CharField(blank=True, max_length=50, null=True)),
                ('codice_evento', models.ForeignKey(blank=True, db_column='codice_evento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.evento')),
            ],
            options={
                'db_table': 'tavolo',
            },
        ),
        migrations.CreateModel(
            name='Biglietto',
            fields=[
                ('codice_biglietto', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('prezzo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('codice_evento', models.ForeignKey(blank=True, db_column='codice_evento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.evento')),
                ('codice_tavolo', models.ForeignKey(blank=True, db_column='codice_tavolo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.tavolo')),
            ],
            options={
                'db_table': 'biglietto',
            },
        ),
        migrations.AddField(
            model_name='richiestaprenotazioneserata',
            name='id_utente',
            field=models.ForeignKey(blank=True, db_column='id_utente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.utente'),
        ),
        migrations.CreateModel(
            name='CartaDiCredito',
            fields=[
                ('codice_metodo_di_pagamento', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('numero_di_carta', models.CharField(max_length=20)),
                ('nome_titolare', models.CharField(blank=True, max_length=50, null=True)),
                ('data_di_scadenza', models.DateField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=20, null=True)),
                ('id_utente', models.ForeignKey(blank=True, db_column='id_utente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.utente')),
            ],
            options={
                'db_table': 'carta_di_credito',
            },
        ),
        migrations.CreateModel(
            name='AcquistoBiglietto',
            fields=[
                ('id_acq', models.AutoField(db_column='ID_ACQ', primary_key=True, serialize=False)),
                ('codice_acquisto_biglietto', models.CharField(max_length=10, unique=True)),
                ('data', models.DateField()),
                ('importo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('codice_metodo_di_pagamento', models.ForeignKey(blank=True, db_column='codice_metodo_di_pagamento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.cartadicredito')),
                ('id_utente', models.ForeignKey(blank=True, db_column='id_utente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.utente')),
            ],
            options={
                'db_table': 'acquisto_biglietto',
            },
        ),
        migrations.CreateModel(
            name='AcquistoSerataPrivata',
            fields=[
                ('codice_evento', models.OneToOneField(db_column='codice_evento', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.evento')),
                ('codice_acquisto_serata', models.CharField(max_length=10, unique=True)),
                ('data', models.DateField()),
                ('importo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('codice_metodo_di_pagamento', models.ForeignKey(blank=True, db_column='codice_metodo_di_pagamento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.cartadicredito')),
                ('id_utente', models.ForeignKey(blank=True, db_column='id_utente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.utente')),
            ],
            options={
                'db_table': 'acquisto_serata_privata',
            },
        ),
        migrations.CreateModel(
            name='BigliettoAcquistato',
            fields=[
                ('codice_biglietto', models.OneToOneField(db_column='codice_biglietto', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.biglietto')),
                ('id_acq', models.ForeignKey(db_column='ID_ACQ', on_delete=django.db.models.deletion.DO_NOTHING, to='app.acquistobiglietto')),
            ],
            options={
                'db_table': 'biglietto_acquistato',
            },
        ),
        migrations.CreateModel(
            name='Partecipazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice_artista', models.ForeignKey(db_column='codice_artista', on_delete=django.db.models.deletion.DO_NOTHING, to='app.artista')),
                ('codice_evento', models.ForeignKey(db_column='codice_evento', on_delete=django.db.models.deletion.DO_NOTHING, to='app.evento')),
            ],
            options={
                'db_table': 'partecipazione',
                'unique_together': {('codice_evento', 'codice_artista')},
            },
        ),
        migrations.CreateModel(
            name='Iscrizione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice_lista', models.ForeignKey(db_column='codice_lista', on_delete=django.db.models.deletion.DO_NOTHING, to='app.listapr')),
                ('id_utente', models.ForeignKey(db_column='id_utente', on_delete=django.db.models.deletion.DO_NOTHING, to='app.utente')),
            ],
            options={
                'db_table': 'iscrizione',
                'unique_together': {('codice_lista', 'id_utente')},
            },
        ),
    ]
