# Generated by Django 5.2.3 on 2025-06-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_tavolo_codice_tavolo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='richiestaprenotazioneserata',
            name='stato',
            field=models.CharField(choices=[('A', 'Acettata'), ('R', 'Rifiutata')], max_length=1),
        ),
    ]
