# Generated by Django 5.2.3 on 2025-06-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_richiestaprenotazioneserata_stato'),
    ]

    operations = [
        migrations.AddField(
            model_name='richiestaprenotazioneserata',
            name='nome_evento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
