# Generated by Django 5.2.3 on 2025-06-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_richiestaprenotazioneserata_nome_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='richiestaprenotazioneserata',
            name='stato',
            field=models.CharField(choices=[('A', 'Acettata'), ('R', 'Rifiutata'), ('P', 'In attesa di risposta')], max_length=1),
        ),
    ]
