# Generated by Django 5.2.3 on 2025-06-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_biglietto_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biglietto',
            name='tipo',
            field=models.CharField(blank=True, choices=[('S', 'Standard'), ('T', 'Tavolo')], max_length=1, null=True),
        ),
    ]
