# Generated by Django 5.2.3 on 2025-06-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_biglietto_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biglietto',
            name='tipo',
            field=models.CharField(choices=[('S', 'Standard'), ('T', 'Tavolo')], default='S', max_length=1),
        ),
    ]
